on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-expose:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:  
        node-version: '20.x'
        cache: 'npm'

    - name: Install npm dependencies
      run: npm install

    - name: Install Localtunnel
      run: npm install -g localtunnel

    - name: Start Localtunnel
      run: |
        lt --port 3000 &  # Starts localtunnel without a subdomain on port 3000
        sleep 5  # Wait for localtunnel to initialize

    - name: Display Localtunnel URL
      run: |
        curl -s localhost:4040/api/tunnels | jq '.tunnels[0].public_url'

    - name: Start server
      run: node server.js
