on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-expose:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:  
        node-version: '20.x'
        cache: 'npm'

    - name: Install npm dependencies
      run: npm install

    - name: Get Public IP
      run: curl https://ipinfo.io/ip


    - name: Start server after tunnel
      run: |
        # Run the server after the tunnel has been set up
        node server.js
