on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-expose:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Install Telebit
      run: |
        curl -s https://get.telebit.io/ | bash
        sudo mv telebit /usr/local/bin/

   

    - name: Start Telebit Tunnel
      run: |
        # Generate a random subdomain using the current timestamp
        SUBDOMAIN=$(date +%s | sha256sum | base64 | head -c 10)
        nohup telebit http 3000 --subdomain $SUBDOMAIN &
        sleep 5  # Wait for the tunnel to start

    - name: Get Public URL
      run: |
        sleep 5  # Wait for Telebit to generate the public URL
        echo "Your Public URL: https://$SUBDOMAIN.telebit.io"


         - name: Start Server
        run: |
        nohup node server.js &
